name: Kitescratch Tests

on: [push]

env:
  NO_INTERACTION: "true"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v4
        with:
          go-version-file: cmd/kitehelper/go.mod

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic requests # Some tests require this

      - name: Tests
        run: |
          cd cmd/kitehelper
          go build -v 
          ./kitehelper test
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Kitescratch: CI Task"
          commit_user_name: "Kitescratch Tests[bot]"